Match gccgo error messages.
bug165.go:13:6: error: invalid recursive type 'S'

This is a different line from the 6g error message, which is
"invalid map key type".  I accomodated both compilers by
merging the line.

bug188.go:13:2: error: unexpected reference to package

I made the error message less specific, which I think is fine
here.

R=rsc
DELTA=2  (0 added, 0 deleted, 2 changed)
OCL=33398
CL=33426