doc: fix codewalk/markov.go
When I build it, I got:
/home/njubee/work/golang/doc/codewalk/markov.go:124: undefined: time.Nanoseconds
time.Nanoseconds() does not exist now, use time.Now().UnixNano() instead

R=golang-dev, adg
CC=golang-dev
http://codereview.appspot.com/5668044

Committer: Andrew Gerrand <adg@golang.org>